# Generated by Django 3.2.11 on 2022-02-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=30)),
                ('reviewTitle', models.CharField(max_length=200)),
                ('reviewDate', models.DateField(auto_now_add=True)),
                ('reviewRate', models.IntegerField()),
                ('reviewTxt', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
