# Generated by Django 3.2.11 on 2022-01-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('userEmail', models.CharField(max_length=30)),
                ('userPw', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('bookId', models.CharField(max_length=30)),
                ('reviewId', models.IntegerField(primary_key=True, serialize=False)),
                ('reviewTxt', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.user')),
            ],
        ),
    ]
