# Generated by Django 3.2.11 on 2022-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewt',
            name='id',
        ),
        migrations.AlterField(
            model_name='reviewt',
            name='reviewId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
